CREATE TABLE `AccountTypes` (
	`AccountTypeID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
CREATE TABLE `TransactionTypes` (
	`TransactionTypeID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
CREATE TABLE `AccountStatuses` (
	`AccountStatusID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
CREATE TABLE `CardStatuses` (
	`CardStatusID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
CREATE TABLE "CardTypes" (
	`CardTypeID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT NOT NULL
);
CREATE TABLE `TransactionStatuses` (
	`TransactionStatusID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT
);
CREATE TABLE "Customers" (
	`CustomerID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FirstName`	TEXT NOT NULL,
	`LastName`	TEXT NOT NULL,
	`Login`	TEXT NOT NULL,
	`Password`	TEXT NOT NULL,
	`CreateDate`	TEXT NOT NULL,
	`IsActive`	INTEGER NOT NULL,
	`LastLogin`	TEXT
);
CREATE TABLE "Transactions" (
	`TransactionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`DateOfTransaction`	TEXT NOT NULL,
	`TransactionTypeID`	INTEGER NOT NULL,
	`Value`	INTEGER NOT NULL,
	`Description`	INTEGER NOT NULL,
	`TransactionStatusID`	INTEGER NOT NULL,
	`SourceAcountID`	INTEGER NOT NULL,
	`SourceCardID`	INTEGER,
	`DestinationAccountID`	INTEGER NOT NULL
);
CREATE TABLE "Cards" (
	`CardID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CardNumber`	TEXT NOT NULL,
	`CardTypeID`	INTEGER NOT NULL,
	`Validity`	TEXT NOT NULL,
	`Buying limit`	INTEGER NOT NULL,
	`CashWithdrawLimit`	INTEGER NOT NULL,
	`Limit`	INTEGER,
	`AccountID`	INTEGER NOT NULL,
	`CardStatusID`	INTEGER NOT NULL
);
CREATE TABLE "Accounts" (
	`AccountID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`CustomerID`	INTEGER NOT NULL,
	`Number`	TEXT NOT NULL,
	`AccountTypeID`	BLOB NOT NULL,
	`AccountStatusID`	INTEGER NOT NULL,
	`OpenDate`	TEXT NOT NULL,
	`Balance`	INTEGER NOT NULL,
	`DebitLine`	INTEGER,
	`Interest`	INTEGER NOT NULL
);
